### PR TITLE
Fix race condition when multiple roles update

### LINKED ISSUE #359: Set room roles: Random role does not get saved
A school reported they had struggle setting user (teachers) as guest for all rooms.

I could reproduce the error:

1. I selected a User assigned all room but the main room to guest role
2. Saved the edit
3. When I opended the set room roles view one of the rooms was not guest see screenshoots

Image
Image

### PR DESCRIPTION
**Pull request by aivuk**
## Context 

Fix #359 

when multiple request to addUserRole or deleteUserRole where being made to the same user, a race condition was happening and the sequential requests were getting the old roles value before the update for earlier requests. The solution was using a transaction and also the FOR UPDATE in the select query to get the roles, without that just a transaction didn't solve the issue. 

## Checklist

- [x] Tested manually 
- [x] GitHub issue linked 
- [ ] Changelist updated
- [x] Backward and forward compatible with [aula-frontend/releases](https://github.com/aula-app/aula-frontend/releases) 
- [x] Doesn't need update in the database 
- [x] Must be deployed ASAP (HOTFIX)
- [ ] Needs update of [docs.aula.de](https://docs.aula.de/) ([repo](https://github.com/leonard-haas/docs_aula))

### CODE REVIEW

File: legacy/src/classes/models/User.php [hunk 1]
```diff
@@ -2195,14 +2195,16 @@ public function addUserRole($user_id, $role, $room_id)
     $user_id = $this->converters->checkUserId($user_id);
     $room_id = $this->converters->checkRoomId($room_id);
 
+    $this->db->beginTransaction();
     $stmt = $this->db->query('SELECT hash_id FROM ' . $this->db->au_rooms . ' WHERE id = :room_id');
     $this->db->bind(':room_id', $room_id);
     $room_hash = $this->db->resultSet()[0]["hash_id"];
```
Comment (nikola-maric-aula) [inline legacy/src/classes/models/User.php]: as far as i understand, there's no need for the first query to be a part of the transaction?
```suggestion
    $stmt = $this->db->query('SELECT hash_id FROM ' . $this->db->au_rooms . ' WHERE id = :room_id');
    $this->db->bind(':room_id', $room_id);
    $room_hash = $this->db->resultSet()[0]["hash_id"];

    $this->db->beginTransaction();
```

File: legacy/src/classes/models/User.php [hunk 2]
```diff
@@ -2320,12 +2323,13 @@ public function deleteUserRole($user_id, $room_id)
     $user_id = $this->converters->checkUserId($user_id); // checks user id and converts user id to db user id if necessary (when user hash id was passed)
     $room_id = $this->converters->checkRoomId($room_id); // checks user id and converts user id to db user id if necessary (when user hash id was passed)
 
+    $this->db->beginTransaction();
     $stmt = $this->db->query('SELECT hash_id FROM ' . $this->db->au_rooms . ' WHERE id = :room_id');
     $this->db->bind(':room_id', $room_id);
     $room_hash = $this->db->resultSet()[0]["hash_id"];
```
Comment (nikola-maric-aula) [inline legacy/src/classes/models/User.php]:
```suggestion
    $stmt = $this->db->query('SELECT hash_id FROM ' . $this->db->au_rooms . ' WHERE id = :room_id');
    $this->db->bind(':room_id', $room_id);
    $room_hash = $this->db->resultSet()[0]["hash_id"];

    $this->db->beginTransaction();
```
